"""empty message

Revision ID: 499aea2ca6be
Revises: 0b8705c2d275
Create Date: 2025-05-26 22:19:12.538491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499aea2ca6be'
down_revision = '0b8705c2d275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=260), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.Column('pass_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_to_be_passed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=260), nullable=False),
    sa.Column('apply_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_be_passed')
    op.drop_table('user')
    # ### end Alembic commands ###
