"""remove foreign key constraints from 8 tables

Revision ID: 3c3a51c1dd39
Revises: f65a8c44e1ef
Create Date: 2025-05-31 18:10:25.388708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3a51c1dd39'
down_revision = 'f65a8c44e1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customer_c_nationkey_fkey'), type_='foreignkey')

    with op.batch_alter_table('lineitem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lineitem_l_suppkey_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lineitem_l_partkey_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lineitem_l_orderkey_fkey'), type_='foreignkey')

    with op.batch_alter_table('nation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('nation_n_regionkey_fkey'), type_='foreignkey')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_o_custkey_fkey'), type_='foreignkey')

    with op.batch_alter_table('partsupp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('partsupp_ps_partkey_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('partsupp_ps_suppkey_fkey'), type_='foreignkey')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('supplier_s_nationkey_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('supplier_s_nationkey_fkey'), 'nation', ['s_nationkey'], ['n_nationkey'])

    with op.batch_alter_table('partsupp', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('partsupp_ps_suppkey_fkey'), 'supplier', ['ps_suppkey'], ['s_suppkey'])
        batch_op.create_foreign_key(batch_op.f('partsupp_ps_partkey_fkey'), 'part', ['ps_partkey'], ['p_partkey'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('orders_o_custkey_fkey'), 'customer', ['o_custkey'], ['c_custkey'])

    with op.batch_alter_table('nation', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('nation_n_regionkey_fkey'), 'region', ['n_regionkey'], ['r_regionkey'])

    with op.batch_alter_table('lineitem', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('lineitem_l_orderkey_fkey'), 'orders', ['l_orderkey'], ['o_orderkey'])
        batch_op.create_foreign_key(batch_op.f('lineitem_l_partkey_fkey'), 'part', ['l_partkey'], ['p_partkey'])
        batch_op.create_foreign_key(batch_op.f('lineitem_l_suppkey_fkey'), 'supplier', ['l_suppkey'], ['s_suppkey'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('customer_c_nationkey_fkey'), 'nation', ['c_nationkey'], ['n_nationkey'])

    # ### end Alembic commands ###
