"""empty message

Revision ID: bfc04643544b
Revises: feba40b3a561
Create Date: 2025-05-29 10:05:31.816694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc04643544b'
down_revision = 'feba40b3a561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('p_partkey', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=55), nullable=False),
    sa.Column('p_mfgr', sa.String(length=25), nullable=False),
    sa.Column('p_brand', sa.String(length=10), nullable=False),
    sa.Column('p_type', sa.String(length=25), nullable=False),
    sa.Column('p_size', sa.Integer(), nullable=False),
    sa.Column('p_container', sa.String(length=10), nullable=False),
    sa.Column('p_retailprice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('p_comment', sa.String(length=23), nullable=False),
    sa.PrimaryKeyConstraint('p_partkey')
    )
    op.create_table('region',
    sa.Column('r_regionkey', sa.Integer(), nullable=False),
    sa.Column('r_name', sa.String(length=25), nullable=False),
    sa.Column('r_comment', sa.String(length=152), nullable=True),
    sa.PrimaryKeyConstraint('r_regionkey')
    )
    op.create_table('nation',
    sa.Column('n_nationkey', sa.Integer(), nullable=False),
    sa.Column('n_name', sa.String(length=25), nullable=False),
    sa.Column('n_regionkey', sa.Integer(), nullable=False),
    sa.Column('n_comment', sa.String(length=152), nullable=True),
    sa.ForeignKeyConstraint(['n_regionkey'], ['region.r_regionkey'], ),
    sa.PrimaryKeyConstraint('n_nationkey')
    )
    op.create_table('customer',
    sa.Column('c_custkey', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=25), nullable=False),
    sa.Column('c_address', sa.String(length=40), nullable=False),
    sa.Column('c_nationkey', sa.Integer(), nullable=False),
    sa.Column('c_phone', sa.String(length=15), nullable=False),
    sa.Column('c_acctbal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('c_mktsegment', sa.String(length=10), nullable=False),
    sa.Column('c_comment', sa.String(length=117), nullable=False),
    sa.ForeignKeyConstraint(['c_nationkey'], ['nation.n_nationkey'], ),
    sa.PrimaryKeyConstraint('c_custkey')
    )
    op.create_table('supplier',
    sa.Column('s_suppkey', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=25), nullable=False),
    sa.Column('s_address', sa.String(length=40), nullable=False),
    sa.Column('s_nationkey', sa.Integer(), nullable=False),
    sa.Column('s_phone', sa.String(length=15), nullable=False),
    sa.Column('s_acctbal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('s_comment', sa.String(length=101), nullable=False),
    sa.ForeignKeyConstraint(['s_nationkey'], ['nation.n_nationkey'], ),
    sa.PrimaryKeyConstraint('s_suppkey')
    )
    op.create_table('orders',
    sa.Column('o_orderkey', sa.Integer(), nullable=False),
    sa.Column('o_custkey', sa.Integer(), nullable=False),
    sa.Column('o_orderstatus', sa.String(length=1), nullable=False),
    sa.Column('o_totalprice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('o_orderdate', sa.Date(), nullable=False),
    sa.Column('o_orderpriority', sa.String(length=15), nullable=False),
    sa.Column('o_clerk', sa.String(length=15), nullable=False),
    sa.Column('o_shippriority', sa.Integer(), nullable=False),
    sa.Column('o_comment', sa.String(length=79), nullable=False),
    sa.ForeignKeyConstraint(['o_custkey'], ['customer.c_custkey'], ),
    sa.PrimaryKeyConstraint('o_orderkey')
    )
    op.create_table('partsupp',
    sa.Column('ps_partkey', sa.Integer(), nullable=False),
    sa.Column('ps_suppkey', sa.Integer(), nullable=False),
    sa.Column('ps_availqty', sa.Integer(), nullable=False),
    sa.Column('ps_supplycost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ps_comment', sa.String(length=199), nullable=False),
    sa.ForeignKeyConstraint(['ps_partkey'], ['part.p_partkey'], ),
    sa.ForeignKeyConstraint(['ps_suppkey'], ['supplier.s_suppkey'], ),
    sa.PrimaryKeyConstraint('ps_partkey', 'ps_suppkey')
    )
    op.create_table('lineitem',
    sa.Column('l_orderkey', sa.Integer(), nullable=False),
    sa.Column('l_partkey', sa.Integer(), nullable=False),
    sa.Column('l_suppkey', sa.Integer(), nullable=False),
    sa.Column('l_linenumber', sa.Integer(), nullable=False),
    sa.Column('l_quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('l_extendedprice', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('l_discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('l_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('l_returnflag', sa.String(length=1), nullable=False),
    sa.Column('l_linestatus', sa.String(length=1), nullable=False),
    sa.Column('l_shipdate', sa.Date(), nullable=False),
    sa.Column('l_commitdate', sa.Date(), nullable=False),
    sa.Column('l_receiptdate', sa.Date(), nullable=False),
    sa.Column('l_shipinstruct', sa.String(length=25), nullable=False),
    sa.Column('l_shipmode', sa.String(length=10), nullable=False),
    sa.Column('l_comment', sa.String(length=44), nullable=False),
    sa.ForeignKeyConstraint(['l_orderkey'], ['orders.o_orderkey'], ),
    sa.ForeignKeyConstraint(['l_partkey'], ['part.p_partkey'], ),
    sa.ForeignKeyConstraint(['l_suppkey'], ['supplier.s_suppkey'], ),
    sa.PrimaryKeyConstraint('l_orderkey', 'l_linenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineitem')
    op.drop_table('partsupp')
    op.drop_table('orders')
    op.drop_table('supplier')
    op.drop_table('customer')
    op.drop_table('nation')
    op.drop_table('region')
    op.drop_table('part')
    # ### end Alembic commands ###
