"""create indexes

Revision ID: fbfd846e9fd9
Revises: 3c3a51c1dd39
Create Date: 2025-06-07 11:05:29.762087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfd846e9fd9'
down_revision = '3c3a51c1dd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('index_customer_name', ['c_name'], unique=False)

    with op.batch_alter_table('lineitem', schema=None) as batch_op:
        batch_op.create_index('index_lineitem_commitdate', ['l_commitdate'], unique=False)
        batch_op.create_index('index_lineitem_orderkey', ['l_orderkey'], unique=False)
        batch_op.create_index('index_lineitem_shipdate', ['l_shipdate'], unique=False)
        batch_op.create_index('index_lineitem_suppkey', ['l_suppkey'], unique=False)

    with op.batch_alter_table('nation', schema=None) as batch_op:
        batch_op.create_index('index_nation_name', ['n_name'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('index_orders_orderdate', ['o_orderdate'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=True)
        batch_op.create_index('idx_user_username', ['username'], unique=True)

    with op.batch_alter_table('user_to_be_passed', schema=None) as batch_op:
        batch_op.create_index('idx_user_to_be_passed_email', ['email'], unique=True)
        batch_op.create_index('idx_user_to_be_passed_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_be_passed', schema=None) as batch_op:
        batch_op.drop_index('idx_user_to_be_passed_username')
        batch_op.drop_index('idx_user_to_be_passed_email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('index_orders_orderdate')

    with op.batch_alter_table('nation', schema=None) as batch_op:
        batch_op.drop_index('index_nation_name')

    with op.batch_alter_table('lineitem', schema=None) as batch_op:
        batch_op.drop_index('index_lineitem_suppkey')
        batch_op.drop_index('index_lineitem_shipdate')
        batch_op.drop_index('index_lineitem_orderkey')
        batch_op.drop_index('index_lineitem_commitdate')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('index_customer_name')

    # ### end Alembic commands ###
